export default {
    perfil03: require('./pessoa1.png'),
    perfil02: require('./pessoa2.png'),
    perfil01: require('./pessoa3.png'),
    perfil04: require('./pessoa4.png'),
    perfil05: require('./pessoa5.jpg'),
    perfil06: require('./pessoa6.jpg'),
    perfil07: require('./homem.png'),
    perfil08: require('./8.jpg'),
    perfil09: require('./9.jpg'),
    perfil10: require('./10.png'),
    perfil11: require('./h2.png'),
    perfil12: require('./h3.png'),
    perfil13: require('./h4.png'),
    perfil14: require('./m.png'),
    perfil15: require('./m2.jpg'),
    perfil16: require('./homenn.png'),
    perfil17: require('./m3.jpg'),
    perfil18: require('./m4.png'),
    perfil19: require('./homennn.png'),
    perfil20: require('./m5.jpg'),
    perfil21: require('./icone.png'),
};